# Generated by Django 3.0.5 on 2021-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
